### Get all blogs
GET http://localhost:3000/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzdWFyaW9fdGVzdGVAdGVzdGUuY29tIiwiaWQiOjYsImlhdCI6MTc0NjkyNzM2MX0.NLrUZyezeE68GYYTYxR-ar5a9vai3MBMw57gWoUG_es

### Create a new blog
POST http://localhost:3000/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzdWFyaW9fdGVzdGVAdGVzdGUuY29tIiwiaWQiOjYsImlhdCI6MTc0NjkyNzM2MX0.NLrUZyezeE68GYYTYxR-ar5a9vai3MBMw57gWoUG_es

{
  "title": "Test Blog",
  "author": "John Doe",
  "url": "https://example.com/test-blog",
  "likes": 5
}

### Delete a blog
DELETE http://localhost:3000/api/blogs/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzdWFyaW9fdGVzdGVAdGVzdGUuY29tIiwiaWQiOjYsImlhdCI6MTc0NjkyNzM2MX0.NLrUZyezeE68GYYTYxR-ar5a9vai3MBMw57gWoUG_es

### Update a blog
PUT http://localhost:3000/api/blogs/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzdWFyaW9fdGVzdGVAdGVzdGUuY29tIiwiaWQiOjYsImlhdCI6MTc0NjkyNzM2MX0.NLrUZyezeE68GYYTYxR-ar5a9vai3MBMw57gWoUG_es

{
  "likes": 10
}