### Get all blogs
GET http://localhost:3000/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzdWFyaW9fdGVzdGVAdGVzdGUuY29tIiwiaWQiOjEsImlhdCI6MTc0NjkzMzc3MH0.yZoDN7gFdNW9GvvgFgwVWRhMyjYFO7sDLw8rUUwA75U


### Create a new blog
POST http://localhost:3000/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzdWFyaW9fdGVzdGVAdGVzdGUuY29tIiwiaWQiOjEsImlhdCI6MTc0NjkzMzc3MH0.yZoDN7gFdNW9GvvgFgwVWRhMyjYFO7sDLw8rUUwA75U

{
  "title": "Test Blog",
  "author": "Jhonny Cash",
  "url": "https://example.com/test-blog",
  "year": 1992
}

### Delete a blog
DELETE http://localhost:3000/api/blogs/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzdWFyaW9fdGVzdGVAdGVzdGUuY29tIiwiaWQiOjEsImlhdCI6MTc0NjkzMzc3MH0.yZoDN7gFdNW9GvvgFgwVWRhMyjYFO7sDLw8rUUwA75U

### Update a blog
PUT http://localhost:3000/api/blogs/9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzdWFyaW9fdGVzdGVAdGVzdGUuY29tIiwiaWQiOjEsImlhdCI6MTc0NjkzMzc3MH0.yZoDN7gFdNW9GvvgFgwVWRhMyjYFO7sDLw8rUUwA75U

{
  "likes": 6
}