### Obter todos os usuários
GET http://localhost:3000/api/users

### Criar um novo usuário
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "username": "usuario_teste@teste.com",
  "name": "Usuário de Teste"
}

### Atualizar um usuário
PUT http://localhost:3000/api/users/usuario_teste_atualizado@teste.com
Content-Type: application/json

{
  "username": "usuario_teste_atualizado"
}

### Get a user by id
GET http://localhost:3000/api/users/1

